agile_assignment/hello/config/routes.rb
Hello::Application.routes.draw do
  get "sessions/new"

  get "users/new"

  get "users/create"

  get "articles/index"

  get "articles/new"

  get "articles/edit"
  
  get "articles/detail/:id" => "articles#detail", :as => "articles_detail"
  
  get "admin/articles/detail/:id" => "admin/articles#detail" , :as => "articles_detail"

  get "books/gallery"

  get "books/author"

  get "say/hello"

  get "say/goodbye"

  get "register" => "users#new", :as => "register"
  
  get "login" => "sessions#new", :as => "login"  

  get "logout" => "sessions#destroy", :as => "logout"

    resources :articles, :users, :sessions, :comments

namespace :admin do
  resources :articles
end

  root :to => "sessions#new"

end

agile_assignment/hello/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @hello = "you say hello and i say goodbye"
    @files = Dir.glob("*")
    @par = params
    @menu = Menus.select("url,label").all
    @param = params[:hendra]
    if @param == "ganteng"
      @hendra = "lol bener haha asik"
      render "./books/author"
    elsif @param == "lol"
      redirect_to books_author_path
    elsif @param == "json"
      s = '{"address":null,"age":null,"birthday":null,"created_at":"2012-09-12T02:53:30Z","email":null,"first_name":null,"id":1,"last_name":null,"updated_at":"2012-09-12T02:53:30Z","username":"hendra"}'
      @x = JSON.parse(s)
      render "./books/author"
    end
  end

  def goodbye
    @goodbye = "Have a Nice Day"
  end
end

agile_assignment/hello/app/helpers/say_helper.rb
module SayHelper
end

agile_assignment/hello/app/views/say/goodbye.html.erb
<%= link_to @goodbye, say_hello_path %>

agile_assignment/hello/app/views/say/hello.html.erb
<%= link_to @hello, say_goodbye_path %>
<br />
<%= 1+2 %>
<br />
<%= 
  "cow" + "boy" 
  @par["hello"]
%>
<br />
<%= 1.hour.from_now %>

<ul>
<% for file in @files %>
<li><%= file %></li>
<% end %>
</ul>

<br />

<ul>
<% @menu.each do |omenu| %>
<li><a href="<%= omenu.url %>"><%= omenu.label %></a></li>
<% end %>
</ul>