agile_assignment/hello/config/routes.rb
Hello::Application.routes.draw do
  get "sessions/new"

  get "users/new"

  get "users/create"

  get "articles/index"

  get "articles/new"

  get "articles/edit"
  
  get "articles/detail/:id" => "articles#detail", :as => "articles_detail"
  
  get "admin/articles/detail/:id" => "admin/articles#detail" , :as => "articles_detail"

  get "books/gallery"

  get "books/author"

  get "say/hello"

  get "say/goodbye"

  get "register" => "users#new", :as => "register"
  
  get "login" => "sessions#new", :as => "login"  

  get "logout" => "sessions#destroy", :as => "logout"

    resources :articles, :users, :sessions, :comments

namespace :admin do
  resources :articles
end

  root :to => "sessions#new"

end

agile_assignment/hello/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :rating, :user_id
  has_many :comments, :dependent => :destroy
  belongs_to :user
  belongs_to :creator,
             :class_name => "User",
             :foreign_key => "user_id",
             :conditions => "title like '%my country%'"
  
  validates :title,   :presence => true,
                      :uniqueness => true,
                      :allow_blank => false
  
  scope :by_rating, lambda {|rate| where("rating = ?", rate)}
  
  #get article that longer than 100 characters
  def longerthan_100
    buf = Article.where("CHAR_LENGTH(body) > 100")
    buf.each do |data|
      puts "Title : #{data.title} Length : #{data.body.length}"
    end     
  end
end

agile_assignment/hello/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_filter :require_admin_login
  
  #show all articles
  def index
    @site_title = "Hello Project - Admin Access - All Article"
  end
  
  #create new article form
  def new
    @article = Article.new
  end

  #edit article form
  def edit
    @article = Article.find(params[:id])
  end
  
  #delete selected article
  def destroy
    if Article.destroy(params[:id])
      flash[:notice] = "Article Deleted Successfuly"
    else  
      flash[:notice] = "Article Delete Failed"
    end
    redirect_to admin_articles_path
  end

  #create new article process, called from new form
  def create
    params[:article][:user_id] = session[:user_id]
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "New Article Created Succesfully"
      redirect_to admin_articles_path
    elsif
      flash[:notice] = "New Article Create Failed"
      render :action => :new
    end
  end

  #update article process, called from edit form
  def update
    if Article.update(params[:id],params[:article])
      flash[:notice] = "Article Edited Succesfully"
      redirect_to admin_articles_path
    elsif
      flash[:notice] = "Article Edit Failed"
      render :action => index
    end
  end
  
  #ahow articles detail and article comment
  def detail
    @article = Article.find(params[:id]);
    @comments = @article.comments
    @comment = Article.find(params[:id]).comments.new
  end
end

agile_assignment/hello/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :update, :index, :destroy]
  
  #index page, show a list of all articles
  def index
    @site_title = "Hello Project - All Article"
  end

  #create new article form
  def new
    @article = Article.new
  end

  #edit article form
  def edit
    article = Article.where("id = #{params[:id]} and user_id = #{session[:user_id]}").select("id").limit(1)
    if article.count == 0
      flash[:notice] = "You Don't have authorization to edit this article"
      redirect_to articles_path
    end
    @article = Article.find(params[:id])
  end
  
  #delete selected article
  def destroy
    article = Article.where("id = #{params[:id]} and user_id = #{session[:user_id]}").select("id").limit(1)
    if article.count == 0
      flash[:notice] = "You Don't have authorization to delete this article"
    elsif Article.destroy(params[:id])
      flash[:notice] = "Article Deleted Successfuly"
    else  
      flash[:notice] = "Article Delete Failed"
    end
    redirect_to articles_path
  end

  #create new article process, called from new form
  def create
    params[:article][:user_id] = session[:user_id]
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "New Article Created Succesfully"
      redirect_to new_article_path
    elsif
      flash[:notice] = "New Article Create Failed"
      render :action => :new
    end
  end

  #update article process, called from edit form
  def update
    begin
      Article.update(params[:id],params[:article])
      flash[:notice] = "Article Edited Succesfully"
    rescue => e
      flash[:notice] = "Article Edit Failed"
    end
    redirect_to articles_path
  end
  
  #ahow articles detail and article comment
  def detail
    @article = Article.find(params[:id]);
    @comments = @article.comments
    @comment = Article.find(params[:id]).comments.new
  end
end

agile_assignment/hello/app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
  def show_all_articles
    ArticlesHelper.show_all_articles
  end
end

agile_assignment/hello/app/helpers/articles_helper.rb
module ArticlesHelper
end

agile_assignment/hello/app/views/admin/articles/detail.html.erb
<%= link_to "Back to Article List", admin_articles_path %>
<h3 style="color:#ff0000"><%= flash[:notice] %></h3>
<h3><%= @article.title %></h3>
Rating : <%= @article.rating %>
<p><%= @article.body %></p>
<br /><br />
<h4>Comments</h4>
<div id="comments">
  <%= render :partial => "./articles/comments", :locals => {:comments => @comments}  %>
</div>
<br />
<p id="ajax-notice" style="color:#ff0000"></p>
<h4>Add New Comment</h4>
<% unless(current_user.nil?)%>
   <%= form_for @comment, :remote => true, :url => comments_path do |f| -%>
      <%= f.text_area :content %>
      <%= f.hidden_field :article_id, :value => @article.id %>
      <br />
      <%= submit_tag "comment" %>
  <% end -%>
<% end %>

<br />
<%= link_to "Back to Article List", admin_articles_path %>

agile_assignment/hello/app/views/admin/articles/edit.html.erb
<%= link_to "Back to Article List", admin_articles_path %>
<h1>Edit Article</h1>
<h3 style="color:#ff0000"><%= flash[:notice] %></h3>
<%= form_for [:admin, @article] do |f| %>  
  <%= f.hidden_field :id %>
  Title : <%= f.text_field :title %>
  <br />
  Body :<br /> <%= f.text_area :body %>
  <br />
  Rating : <%= f.text_field :rating %>
  <br />
  <%=f.submit%>
<% end %>
<br />
<%= link_to "Back to Article List", admin_articles_path %>

agile_assignment/hello/app/views/admin/articles/index.html.erb
<h3 style="color:#ff0000"><%= flash[:notice] %></h3>
<%= link_to "Add New Article", new_admin_article_path %>
<br />
    <% if Article.count < 1 %>
      <p style='color:#ff0000'>No Article Found, Press Add New Article to Start</p>
    <% end %>
    <table><tr>
    <th>Author</th>
    <th>Title</th>
    <th>Body</th>
    <th>Rating</th>
    <th>Operation</th>
    </tr>
    <% Article.all.each do |article| %>
      <tr>
        <td><%= article.user.full_name %></td>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.rating %></td>
        <td><%= link_to "Details", {:controller => "articles", :action => "detail", :id => article.id} %>
            <%= link_to "Edit", {:controller => "articles", :action => "edit", :id => article.id}%>
            <%= link_to "Delete",admin_article_path(article.id), {:confirm => "Are you sure to delete this article ?", :method => :delete}%>
        </td>
      </tr>
    <% end %>
    </table>
<br />

agile_assignment/hello/app/views/admin/articles/new.html.erb
<%= link_to "Back to Article List", admin_articles_path %>
<h1>Add New Article</h1>
<h3 style="color:#ff0000"><%= flash[:notice] %></h3>
<%= form_for [:admin, @article] do |f| %>  
  Title :<br /> <%= f.text_field :title %>
  <br />
  Body :<br /> <%= f.text_area :body %>
  <br />
  <%=f.submit %>
<% end %>
<br />
<%= link_to "Back to Article List", admin_articles_path %>